Repository puppetlabs/puppetlabs-puppet_operations_appliance, pull requests merged in 2021-01, with the labels that each got.

#12 Feature - PE Client tools Deployment
  .ruby-version
  lib/puppet/functions/nodegroups.rb
  lib/puppet_x/nodegroups/common.rb
  manifests/importer.pp
  tasks/supportuser.sh
Labels: enhancement

#10 W.I.P. PR2: New functions created to query for each item - calling of functions in importer.pp
  functions/get_postgres_hosts.pp
  functions/get_puppet_servers.pp
  functions/get_puppetdb_hosts.pp
  manifests/importer.pp
Labels: enhancement

#13 Jameslanepuppet [WIP] get_rsan_ip function
  functions/get_rsan_ip.pp
  manifests/exporter.pp
  manifests/importer.pp
Labels: enhancement

#31 Account for non undef postgresql fact
  manifests/exporter.pp
Labels: bug

#39 remove mocha deprecation warnings
  .sync.yml
  spec/spec_helper.rb
Labels: enhancement

#41 Documentation and release prep
  CHANGELOG.md
  README.md
  REFERENCE.md
  manifests/importer.pp
  metadata.json
  tasks/supportsession.json
  tasks/supportsession.sh
  tasks/supportuser.json
Labels: enhancement

#42 Metadata and spelling corrections
  README.md
  metadata.json
Labels: documentation
